# kew word arguments for the http server
http_server: # the server that hosts all http requests to the computer node
    host: "127.0.0.1"
    port: 8080

# kew word arguments passed into the zmq comm line
zmq_comm_line:
    # address of the computer node
    host: "127.0.0.1"
    port: 7777
    neighbors: # the address of all neighboring computer nodes
        - host: "127.0.0.1"
          port: 6666

# key word arguments passed into the serial comm line
serial_comm_line:
    plugged_in: true # true if computer proxy is plugged into computer
    baud_rate: 9600

# key word arguments passed into simulated comm line
sim_comm_line:
    nodes: [21, 22, 23, 24, 25, 26, 27, 28, 29, 210, 211]
