server:
    host: "127.0.0.1"
    port: 8090
computer_node:
    host: "127.0.0.1"
    port: 6666
    neighbors:
        - host: "127.0.0.1"
          port: 5555
has_computer_proxy_node: false #true
simulated_nodes: [21, 22, 23, 24, 25, 26, 27, 28, 29, 210, 211]
